config/routes.rb
Loja::Application.routes.draw do

  root :to => "home#index"
  match 'inicio' => 'home#index'
  resources :produtos
  resources :clientes
  resources :vendedores
  resources :vendas

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base

  has_many :vendas, :dependent => :restrict

  validates_presence_of [:nome,:cpf],:message => '- deve ser preenchido.'
  validates_uniqueness_of :cpf,:message => '- Este CPF já está cadastrado.'
  validates_uniqueness_of :email,:message => '- Este email já está cadastrado.'
  validates_uniqueness_of :telefone,:message => '- Este telefone já está cadastrado.'

end

app/models/produto.rb
class Produto < ActiveRecord::Base

  has_many :vendas, :dependent => :restrict

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates_presence_of [:nome,:descricao,:valor],:message => "- deve ser preenchido."
  validates_uniqueness_of :nome,:message => "- Este nome já está cadastrado."
  validates_numericality_of [:valor,:quantidade],:message => "- deve ser um número."

  scope :em_estoque, :conditions => 'quantidade > 0'

end

app/models/venda.rb
class Venda < ActiveRecord::Base

  belongs_to :produto
  belongs_to :vendedor
  belongs_to :cliente

  validates_presence_of :produto_id, :message => "- Selecione um produto."
  validates_presence_of :vendedor_id, :message => "- Selecione um vendedor."
  validates_presence_of :cliente_id, :message => "- Selecione um cliente."

  after_save :atualizar_estoque

  def atualizar_estoque
    produto = self.produto
    produto.quantidade = produto.quantidade-1
    produto.save
  end

end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base

  has_many :vendas, :dependent => :restrict

  validates_presence_of [:nome,:codigo,:salario],:message => "- deve ser preenchido."
  validates_numericality_of [:codigo,:salario], :message => "- deve ser um número."
  validates_uniqueness_of :nome, :message => "- Este nome já está cadastrado."
  validates_uniqueness_of :codigo, :message => "- Este código já está cadastrado."

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController

  def index
    @clientes = Cliente.order "nome"
  end

  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
    @cliente = Cliente.new
  end

  def create
    @cliente = Cliente.new(params[:cliente])
    if @cliente.save
      redirect_to(@cliente,:notice => "Cliente cadastrado com sucesso!")
    else
      render :action => "new"
    end
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def update
    @cliente = Cliente.find(params[:id])
    if @cliente.update_attributes(params[:cliente])
      redirect_to(@cliente, :notice => "Cliente atualizado com sucesso!")
    else
      render :action => "edit"
    end
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    begin
      @cliente.destroy
      redirect_to(:action => "index")
    rescue ActiveRecord::DeleteRestrictionError => error
      flash[:error] = "O cliente está ligado a uma ou mais vendas e não pode ser excluido."
      redirect_to clientes_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def index
    @produtos = Produto.order "nome"
  end

  def show
    @produto = Produto.find(params[:id])
  end

  def new
    @produto = Produto.new
  end

  def create
    @produto = Produto.new(params[:produto])
    if @produto.save
      redirect_to(@produto,:notice => "Produto cadastrado com sucesso!")
    else
      render :action => "new"
    end
  end

  def edit
    @produto = Produto.find(params[:id])
  end

  def update
    @produto = Produto.find(params[:id])
    if @produto.update_attributes(params[:produto])
      redirect_to(@produto, :notice => "Produto atualizado com sucesso!")
    else
      render :action => "edit"
    end
  end

  def destroy
    @produto = Produto.find(params[:id])
    begin
      @produto.destroy
      redirect_to(:action => "index")
    rescue ActiveRecord::DeleteRestrictionError => error
      flash[:error] = "O produto está ligado a uma ou mais vendas e não pode ser excluido."
      redirect_to produtos_path
    end
  end

end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController

  def index
    if params[:nome_cliente] && params[:nome_cliente]!=''
      clientes = Cliente.where(["nome LIKE ?","%#{params[:nome_cliente]}%"])
      if clientes!=nil && clientes!=[]
        @cliente = clientes.first
        @vendas = clientes.first.vendas
      else
        @vendas = []
      end
    else
      @vendas = Venda.all
    end
  end

  def show
    @venda = Venda.find(params[:id])
  end

  def new
    @venda = Venda.new
  end

  def create
    @venda = Venda.new(params[:venda])
    if @venda.save
      redirect_to (@venda, :notice => 'Venda efetuada com sucesso!')
    else
      render :action => "new"
    end
  end

  def update
    @venda = Venda.find(params[:id])
    puts @venda.id
    if @venda.update_attributes(params[:venda])
      redirect_to (@venda, :notice => 'Dados da venda atualizados com sucesso!')
    else
      render :action => 'edit'
    end
  end

  def edit
    @venda = Venda.find(params[:id])
    puts @venda.id
  end

  def destroy
    @venda = Venda.find(params[:id])
    @venda.destroy
    redirect_to :action => 'index'
  end

end

app/controllers/vendedores_controller.rb
class VendedoresController < ApplicationController

  def index
    @vendedores = Vendedor.order "nome"
  end

  def new
    @vendedor = Vendedor.new
  end

  def create
    @vendedor = Vendedor.new(params[:vendedor])
    if @vendedor.save
      redirect_to(@vendedor,:notice => "Vendedor cadastrado com sucesso!")
    else
      render :action => "new"
    end
  end

  def edit
    @vendedor = Vendedor.find(params[:id])
  end

  def update
    @vendedor = Vendedor.find(params[:id])
    if @vendedor.update_attributes(params[:vendedor])
      redirect_to(@vendedor,:notice => "Vendedor atualiza com sucesso!")
    else
      render :action => "edit"
    end
  end


  def show
    @vendedor = Vendedor.find(params[:id])
  end

  def destroy
    @vendedor = Vendedor.find(params[:id])
    begin
      @vendedor.destroy
      redirect_to(:action => "index")
    rescue ActiveRecord::DeleteRestrictionError => error
      flash[:error] = "O vendedor está ligado a uma ou mais vendas e não pode ser excluido."
      redirect_to vendedores_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def formato_moeda_real(valor)
    number_to_currency(valor,:unit=>'R$',:separator=>',',:delimiter=>'.')
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/helpers/vendedores_helper.rb
module VendedoresHelper
end

app/views/clientes/_form.html.erb
<% if @cliente.errors.any? %>
  <ul>
    <% @cliente.errors.full_messages.each do |msg| %>
      <li><font color='RED'><%= msg %></font></li>
    <% end %>
  </ul>
<% end %>

<%= form_for (@cliente) do |f| %>
  Nome:<br/><%= f.text_field :nome%><br/>
  CPF:<br/><%= f.text_field :cpf%><br/>
  Email:<br/><%= f.text_field :email%><br/>
  Telefone:<br/><%= f.text_field :telefone%><br/>
  <br/>
  <% if @cliente.new_record? %>
    <%= submit_tag 'Cadastrar' %>
  <% else %>
    <%= submit_tag 'Atualizar' %>
  <% end %>
<% end %>
<br/>
<%= link_to 'Voltar', clientes_path %>

app/views/clientes/edit.html.erb
<h1> Alterando dados do cliente </h1>

<%= render 'form' %>

app/views/clientes/index.html.erb
<h1> Lista de clientes </h1>

<table cellpadding=10>
  <tr bgcolor='#4B7399' style='color:white'>
    <th> Nome </th>
    <th> CPF </th>
    <th> Email </th>
    <th> Telefone </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @clientes.each do |cliente| %>
    <tr>
      <td><%= cliente.nome%></td>
      <td><%= cliente.cpf%></td>
      <td><%= cliente.email%></td>
      <td><%= cliente.telefone%></td>
      <td><%= link_to 'Mostrar', cliente%></td>
      <td><%= link_to 'Editar', edit_cliente_path(cliente)%></td>
      <td><%= link_to 'Excluir', cliente, :method => 'delete', :confirm => "Tem certeza?"%></td>
    </tr>
  <% end %>
</table>
<br/>
<%= link_to 'Cadastrar cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1> Cadastrando cliente </h1>

<%= render 'form' %>

app/views/clientes/show.html.erb
<h1> Exibindo cliente </h1>

<p>
  <b>Nome:</b>
  <%=@cliente.nome%>
</p>

<p>
  <b>CPF:</b>
  <%=@cliente.cpf%>
</p>

<p>
  <b>Email:</b>
  <%=@cliente.email%>
</p>

<p>
  <b>Telefone:</b>
  <%=@cliente.telefone%>
</p>

<%= link_to 'Editar', edit_cliente_path(@cliente) %>
<%= link_to 'Voltar', clientes_path %>

app/views/home/index.html.erb
<h3>
  Bem vindo
  <br/>
  <br/>
  Na Loja você compra tudo pelo menor preço.
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Loja" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%=link_to 'Início', :controller => 'home', :action => 'index' %> -
      <%=link_to 'Clientes', clientes_path%> - <%=link_to 'Produtos', produtos_path%> -
      <%=link_to 'Vendedores', vendedores_path%> - <%=link_to 'Vendas', vendas_path%>
      <br/>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/_form.html.erb
<% if @produto.errors.any? %>
  <ul>
    <%@produto.errors.full_messages.each do |msg| %>
      <li><font color='RED'><%= msg %> </font></li>
    <% end %>
  </ul>
<% end %>


<%form_for (@produto, :html => { :multipart => true }) do |f| %>
  Nome: <br/><%= f.text_field :nome %><br/>
  Descrição: <br/><%= f.text_field :descricao %><br/>
  Valor: <br/><%= f.text_field :valor %><br/>
  Quantidade: <br/><%= f.text_field :quantidade %><br/>
  Foto: <%= f.file_field :avatar %><br/>
  <br/>
  <% if @produto.new_record? %>
    <%= submit_tag 'Cadastrar' %>
  <% else %>
    <%= submit_tag 'Atualizar' %>
  <% end %>
<% end %>
<br/>
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/edit.html.erb
<h1> Editando produto </h1>

<%= render 'form' %>

app/views/produtos/index.html.erb
<h1> Lista de produtos </h1>

<table cellpadding=10>
  <tr bgcolor='#4B7399' style='color:white'>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Valor</th>
    <th>Quantidade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @produtos.each do |produto| %>
  <tr>
    <td> <%=produto.nome%> </td>
    <td> <%=produto.descricao%> </td>
    <td> <%=formato_moeda_real(produto.valor)%> </td>
    <td> <%=produto.quantidade%> </td>
    <td> <%= link_to 'Mostrar', produto%></td>
    <td> <%= link_to 'Editar', edit_produto_path(produto)%></td>
    <td> <%= link_to 'Excluir', produto, :confirm => "Tem certeza?", :method => :delete %></td>
  </tr>
  <% end %>
</table>
</br>
<%= link_to 'Cadastrar Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>Cadastro de produto</h1>

<%= render 'form' %>

app/views/produtos/show.html.erb
<h1> Exibindo produto </h1>

<p>
  <b> Nome: </b>
  <%= @produto.nome %>
</p>

<p>
  <b> Descrição: </b>
  <%= @produto.descricao %>
</p>

<p>
  <b> Valor: </b>
  <%= formato_moeda_real(@produto.valor) %>
</p>

<p>
  <b> Quantidade: </b>
  <%= @produto.quantidade %>
</p>

<p>
  <b> Foto: </b>
  <%= image_tag @produto.avatar.url(:medium) %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto) %>
<%= link_to 'Voltar', produtos_path %>

app/views/vendas/_form.html.erb
<% if @venda.errors.any? %>
  <ul>
    <%@venda.errors.full_messages.each do |msg| %>
      <li><font color='RED'><%= msg %> </font></li>
    <% end %>
  </ul>
<% end %>

<%form_for (@venda) do |f| %>
  Produto: <br/><%= f.collection_select(:produto_id,Produto.em_estoque.order(:nome),:id,:nome,{:include_blank=>'Selecione um produto'}) %><br/>
  Vendedor: <br/><%= f.collection_select(:vendedor_id,Vendedor.order(:nome),:id,:nome,{:include_blank=>'Selecione um vendedor'}) %><br/>
  Cliente: <br/><%= f.collection_select(:cliente_id,Cliente.order(:nome),:id,:nome,{:include_blank=>'Selecione um cliente'}) %><br/>
  <br/>
  <% if @venda.new_record? %>
    <%= submit_tag 'Efetuar venda' %>
  <% else %>
    <%= submit_tag 'Atualizar dados da venda' %>
  <% end %>
<% end %>
<br/>
<%= link_to 'Voltar', vendas_path %>

app/views/vendas/edit.html.erb
<h1> Alterando dados da venda </h1>

<%= render 'form' %>

app/views/vendas/index.html.erb
<% if @cliente!=nil%>
  <h2>Lista de vendas feitas ao cliente <%=@cliente.nome %></h2>
<% else %>
  <h2> Lista de todas as vendas</h2>
<% end %>

<p>
  <%= form_tag vendas_path, :method => 'get' do %>
  <%= text_field_tag :nome_cliente, params[:nome_cliente] %>
  <%= submit_tag "Buscar por Cliente" , :name => nil%>
  <% end %>
</p>
<br/>

<table cellpadding=10>

  <tr bgcolor='#4B7399' style='color:white'>
    <th>Produto</th>
    <th>Vendedor</th>
    <th>Cliente</th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>
  <% @vendas.each do |venda| %>
    <tr>
      <td><%= venda.produto.nome%></td>
      <td><%= venda.vendedor.nome%></td>
      <td><%= venda.cliente.nome%></td>
      <td><%= link_to 'Mostrar', venda%></td>
      <td><%= link_to 'Editar', edit_venda_path(venda)%></td>
      <td><%= link_to 'Excluir', venda, :confirm => 'Tem certeza?', :method => :delete%></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'Efetuar venda', new_venda_path%>

app/views/vendas/new.html.erb
<h1> Venda de produto </h1>

<%= render 'form'%>

app/views/vendas/show.html.erb
<h1> Exibindo venda </h1>

<p>
  <b>Produto:</b>
  <%=@venda.produto.nome%>
</p>

<p>
  <b>Vendedor:</b>
  <%=@venda.vendedor.nome%>
</p>

<p>
  <b>Cliente:</b>
  <%=@venda.cliente.nome%>
</p>


<%= link_to 'Editar', edit_venda_path(@venda)%>
<%= link_to 'Voltar', vendas_path(@venda)%>

app/views/vendedores/_form.html.erb
<% if @vendedor.errors.any? %>
  <ul>
    <%@vendedor.errors.full_messages.each do |msg| %>
      <li><font color='RED'><%= msg %></font></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@vendedor) do |f| %>
  Nome:<br/><%= f.text_field :nome %><br/>
  Código:<br/><%= f.text_field :codigo %><br/>
  Salário:<br/><%= f.text_field :salario %><br/>
  <br/>
  <% if @vendedor.new_record? %>
    <%= submit_tag 'Cadastrar' %>
  <% else %>
    <%= submit_tag 'Atualizar' %>
  <% end %>
<% end %>
<br/>
<%= link_to 'Voltar',vendedores_path %>

app/views/vendedores/edit.html.erb
<h1> Editando vendedor </h1>

<%= render 'form' %>

app/views/vendedores/index.html.erb
<h1> Lista de vendedores </h1>

<table cellpadding=10>
  <tr bgcolor='#4B7399' style='color:white'>
    <th>Nome</th>
    <th>Código</th>
    <th>Salário</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @vendedores.each do |vendedor| %>
    <tr>
      <td><%= vendedor.nome%></td>
      <td><%= vendedor.codigo%></td>
      <td><%= formato_moeda_real(vendedor.salario) %></td>
      <td><%= link_to 'Mostrar', vendedor%></td>
      <td><%= link_to 'Editar', edit_vendedor_path(vendedor)%></td>
      <td><%= link_to 'Excluir', vendedor,:method => 'delete', :confirm => "Tem certeza?" %></td>
    </tr>
  <% end %>
</table>
</br>
<%= link_to 'Cadastrar Vendedor', new_vendedor_path %>

app/views/vendedores/new.html.erb
<h1> Cadastro de vendedor </h1>

<%= render 'form' %>

app/views/vendedores/show.html.erb
<h1> Exibindo o vendedor </h1>

<p>
  <b> Nome: </b>
  <%= @vendedor.nome %>
</p>

<p>
  <b> Código: </b>
  <%= @vendedor.codigo %>
</p>

<p>
  <b> Salário: </b>
  <%= formato_moeda_real(@vendedor.salario) %>
</p>

<%= link_to 'Editar', edit_vendedor_path(@vendedor) %>
<%= link_to 'Voltar', vendedores_path %>